[tool.poetry]
name = "itu-p1203"
version = "1.7.0"
description = "ITU-T P.1203 Standalone Model"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.19.2"
scipy = "^1.5.2"
pandas = "^1.1.2"

[tool.poetry.dev-dependencies]
gitchangelog = "^3.0.4"
pystache = "^0.5.4"

[tool.poetry.scripts]
p1203-standalone = 'itu_p1203.__main__:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
